inventario_dicc = {
    "Guantes": ["tamaño S"],
    "Guantes": ["tamaño M"],
    "Guantes": ["tamaño G"],
    "Jeringas": ["10 cm³"],
    "Jeringas": ["20 cm³"],
    "Jeringas": ["5 cc"],
    "Jeringas": ["3 cc"],
    "Jeringas": ["1 ml"],
    "Agujas": ["25/8"],
    "Agujas": ["16/5"],
    "Agujas": ["40/8"],
    "Agujas": ["50/8"],
    "Algodón": "Algodón",
    "Alcohol": "Alcohol",
    "Catéteres intravenosos": "Catéteres intravenosos",
    "Llave de 3 vías": "Llave de 3 vías",
    "Butter flay": "Butter flay",
    "Prolongadores": ["B14", "B17"],
    "Sondas vesicales para niños": ["10", "12", "14"],
    "Sondas naso-gástricas para niños": ["30", "31"],
    "Máscaras p/nbz":"Máscaras p/nbz",
    "Máscaras de oxígeno": "Máscaras de oxígeno",
    "Cánulas":  "Cánulas",
    "Guías de bomba":"Guías de bomba",
    "Guías de N.E": "Guías de N.E",
    "Agua oxigenada": "Agua oxigenada",
    "Pervinox solución":"Pervinox solución",
    "Pervinox solución jabonosa": "Pervinox solución jabonosa",
    "Gasas": "Gasas",
    "Apósitos":  "Apósitos",
    "Baja lenguas de madera": "Baja lenguas de madera"
}

print(inventario_dicc)
